<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/views/scripts/error/error.phtml $
 * @revision - $Revision: 322 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<?php $this->placeholder('genericErrorMessage')->captureStart(); ?>
  <header>
    <hgroup>
      <h3>Upsss...</h3>
      <h4><?php echo $this->translate($this->message); ?></h4>
    </hgroup>
    <p><?php echo $this->translate('Información relacionada al error ha sido registrada y enviada al administrador para un futuro analisis')?></p>
  </header>
  <?php if (isset($this->exception)): ?>
  <section>
    <h3>Informacion de la Exepción:</h3>
    <p><strong>Mensaje:</b> <?php echo $this->exception->getMessage() ?></strong></p>
    <h3>Orden de ejecución de funciones:</h3>
    <pre><?php echo $this->exception->getTraceAsString() ?></pre>
    <h3>Parametros del Request:</h3>
    <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>
  </section>
  <?php endif ?>
<?php $this->placeholder('genericErrorMessage')->captureEnd(); ?>
