<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/modules/admin/views/scripts/helpers/adminCrud.phtml $
 * @revision - $Revision: 322 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<div id="adminCrud" class="span-5 categories">
  <div class="subcategoriesMargin">
    <h3><?php echo $this->title; ?></h3>
    <menu>
    <?php 
    foreach($this->menu as $item):
    ?>
       <li>
         <a href="<?php echo $item['url'];?>"><?php echo $item['title'];?></a>
       </li>
    <?php 
    endforeach;
    ?>
    </menu>
  </div>
</div>