<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/modules/admin/views/scripts/promotions/index.phtml $
 * @revision - $Revision: 322 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<?php $this->placeholder('catalog')->captureStart(); ?>
<div id="adminPromotionsContainer">
  <form method="<?php echo $this->form->getMethod()?>" action="<?php echo $this->form->getAction(); ?>"
    enctype="<?php echo $this->form->getEnctype();?>">
    <h3>Banners Promocionales</h3>
    <div id="parentCategoryContainer">
      <ul>
        <li><a href="#tabs-parentCategoryContainer">Categoria padre</a></li>
      </ul>
      <div id="tabs-parentCategoryContainer">
        <div id="headerFileHolder"><?php echo $this->form->getElement('headerPromotion'); ?></div>
        <div class="error">El archivo debe ser una imagen <strong>png</strong> de 917px de ancho y 89px de alto</div>
        <div class="headerPromotionAdminHolder">
          <img src="<?php echo APPLICATION_CDN; ?>/images/header.png" width="917" height="89" />
        </div>
        
        <hr />
        <div id="leftFileHolder"><?php echo $this->form->getElement('leftPromotion'); ?></div>
        <div class="error">El archivo debe ser una imagen <strong>jpg</strong> de 550px de ancho y 403px de alto</div>
        <img src="<?php echo APPLICATION_CDN; ?>/images/promotion.jpg" width="550" height="403" />
        
        <hr />
        <div id="rightFileHolder"><?php echo $this->form->getElement('rightPromotion'); ?></div>
        <div class="error">El archivo debe ser una imagen <strong>png</strong> de 350px de ancho y 403px de alto</div>
        <img src="<?php echo APPLICATION_CDN; ?>/images/promotionText.png" width="350" height="403" />
        
        <div id="submitHolder"><?php echo $this->form->getElement('submit'); ?></div>
      </div>
    </div>
    
  </form>
</div>
<?php $this->placeholder('catalog')->captureEnd(); ?>