<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/views/scripts/user/password-reset-mail-sent.phtml $
 * @revision - $Revision: 322 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<?php $this->placeholder('catalog')->captureStart(); ?>
<section id="contactFormHolder">
  <fieldset>
    <legend><?php echo $this->translate('OLVIDE MI CONTRASEÑA')?></legend>
    <div class="passwordSent">
      <p>
        <span class="remark"><?php echo $this->translate('Recibiras un email en tu casilla de correo')?></span>.
        <?php echo $this->translate('En el mismo, encontraras un vinculo, clickealo para activar la nueva contraseña')?>
        .<br />
        <?php echo $this->translate('Este vinculo tiene validez solo por 24 horas')?>
      </p>
    </div>
  </fieldset>
</section>
<?php $this->placeholder('catalog')->captureEnd(); ?>