<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/views/scripts/user/password-reset.phtml $
 * @revision - $Revision: 322 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<?php $this->placeholder('catalog')->captureStart(); ?>
<section id="contactFormHolder">
  <form method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>">
    <?php echo $this->form->getElement('no_csrf'); ?>
    <fieldset>
      <legend><?php echo $this->translate('OLVIDE MI CONTRASEÑA')?></legend>
      <div class="disclaimer">
        <p>
          <?php echo $this->translate('Ingresá tu dirección de correo eletrónico y clickea continuar')?>.
        </p>
      </div>
      <div>
        <label for="email">email</label> <?php echo $this->form->getElement('email'); ?>
        <?php echo $this->form->getElement('submit'); ?>
      </div>
      <?php if ($this->form->getElement('email')->hasErrors()):?>
      <div class="error">
        <?php echo $this->translate('Ese email no se encuentra asociado a ningun usuario registrado')?>
      </div>
      <?php endif;?>
    </fieldset>
  </form>
</section>
<?php $this->placeholder('catalog')->captureEnd(); ?>