<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/views/scripts/user/registration-complete.phtml $
 * @revision - $Revision: 322 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<?php $this->placeholder('headerPromotion')->captureStart(); ?>
<?php echo $this->menuSteps(); ?>
<?php $this->placeholder('headerPromotion')->captureEnd(); ?>
<?php $this->placeholder('catalog')->captureStart(); ?>
<section id="registrationCompleteHolder">
  <fieldset>
    <legend><?php echo $this->translate('Registrate')?></legend>
    <div class="legend">
      <p><?php echo $this->translate('Su registración ha sido exitosa, y deberá ser confirmada')?>.</p>
      <p><?php echo $this->translate('Por favor confirme su registración visitando el vinculo que le hemos enviado por email')?></p>
    </div>
  </fieldset>
</section>
<?php $this->placeholder('catalog')->captureEnd(); ?>