<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/views/scripts/user/reset-password-confirmation.phtml $
 * @revision - $Revision: 322 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<?php $this->placeholder('catalog')->captureStart(); ?>
<section id="resetPasswordConfirmationHolder">
  <fieldset>
    <legend><?php echo $this->translate('OLVIDE MI CONTRASEÑA')?></legend>
    <?php if ($this->password):?>
      <?php echo $this->translate('Su clave ha sido reseteada, esta es su nueva contraseña')?> <?php echo $this->password; ?>
    <?php else: ?>
      <p><?php echo $this->translate('Solo tienes 24 horas para confirmar tu nueva contraseña')?>.</p>
      <p><?php echo $this->translate('Volvé a intentarlo haciendo')?> <a class="remark" href="/olvide-mi-contraseña"><?php echo $this->translate('click aquí')?></a></p>
    <?php endif;?>
  </fieldset>
</section>
<?php $this->placeholder('catalog')->captureEnd(); ?>