<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/views/scripts/user/success.phtml $
 * @revision - $Revision: 322 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<?php $this->placeholder('catalog')->captureStart(); ?>
<h3><?php echo $this->translate('Un email de confirmacion ha sido enviado a su casilla de correo')?>.</h3>
<p><?php echo $this->translate('Antes de proseguir, debera confirmar la misma')?>.<br />
<?php echo $this->translate('Una vez completado el proceso de registro, podra hacer uso completo de nuestro sitio
y recibir el newsletter si asi lo ha indicado')?></p>
<?php $this->placeholder('catalog')->captureEnd(); ?>