<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/views/scripts/user/update-personal-information-success.phtml $
 * @revision - $Revision: 322 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<?php $this->placeholder('headerPromotion')->captureStart(); ?>
<?php echo $this->menuSteps(); ?>
<?php $this->placeholder('headerPromotion')->captureEnd(); ?>
<?php $this->placeholder('catalog')->captureStart(); ?>
<section id="updatePersonalInformationHolder">
  <fieldset>
    <legend><?php echo $this->translate('DATOS PERSONALES')?></legend>
    <div class="legend">
      <?php echo $this->translate('Su datos han sido modificados con exito')?>
    </div>
  </fieldset>
</section>
<?php $this->placeholder('catalog')->captureEnd(); ?>