<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/views/scripts/user/user-already-logged-in.phtml $
 * @revision - $Revision: 322 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<?php $this->placeholder('genericErrorMessage')->captureStart(); ?>
<p><?php echo $this->translate('Un usuario ya se encuentra activo en esta sesión');?></p>
<p><a href="/user/logout-before-login"><?php echo $this->translate('¿Desea ingresar como otro usuario?');?></a></p>
<?php $this->placeholder('genericErrorMessage')->captureEnd(); ?>