<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/views/scripts/_email/html/contact-arrived.phtml $
 * @revision - $Revision: 322 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<p><strong>Nombre:</strong> <?php echo $this->contactData['name']; ?> <?php echo $this->contactData['lastname']; ?></p>
<p><strong>Email:</strong> <?php echo $this->contactData['email']; ?></p>
<p><strong>Tel&eacute;fono:</strong> <?php echo $this->contactData['phone']; ?></p>
<p><strong>Ciudad:</strong> <?php echo $this->contactData['city']; ?></p>
<p><strong>Comentarios:</strong> <?php echo $this->contactData['comments']; ?></p>
