<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/views/scripts/_email/html/password-reset.phtml $
 * @revision - $Revision: 322 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<p><?php echo $this->translate('Hola')?> <span class="remark"><?php echo $this->fullname?></span>,</p>
<p><?php echo $this->translate('Has solicitado un cambio de contrase&ntilde;a. Pero para ello requerimos tu confirmaci&oacute;n.')?><br />
  <?php echo $this->translate('Puedes confirmar el cambio de contrase&ntilde;a haciendo ')?><a target ="_blank" style="color: #A70B16;
  text-decoration:none;" href="<?php echo $this->url?>"><?php echo $this->translate('click aqu&iacute; - Confirmar cambio de contrase&ntilde;a')?></a>
</p>
<p><?php echo $this->translate('Solo tienes 24 horas para confirmar el cambio de contrase&ntilde;a.')?></p>
