<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/views/scripts/_email/html/reset-password-confirmation.phtml $
 * @revision - $Revision: 322 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<p><?php echo $this->translate('Hola')?> <span class="remark"><?php echo $this->fullname?></span>,</p>
<p><?php echo $this->translate('El cambio de contrase&ntilde;a se ha realizado con exito')?></p>
<p><?php echo $this->translate('Esta es tu nueva contrase&ntilde;a')?> <span class="remark"><?php echo $this->password; ?></span>,
  <?php echo $this->translate('la puedes cambiar desde el')?> <a target ="_blank" style="color: #A70B16; text-decoration:none;"
  href="http://<?php echo $_SERVER['HTTP_HOST'];?>/mis-datos"><?php echo $this->translate('panel de usuario')?></a>
</p>
<p><?php echo $this->translate('Recuerda que tu usuario es')?> <span class="remark"><?php echo $this->username; ?></span></p>
