<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/views/scripts/_email/html/welcome.phtml $
 * @revision - $Revision: 322 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<p><?php echo $this->translate('Hola')?> <span class="remark"><?php echo $this->fullname?></span>,</p>
<p><?php echo $this->translate('Bienvenido a Vassilymas. Antes de poder ingresar te requerimos la confirmacion de la cuenta.<br />Esto lo hacemos para que nadie pueda registrar emails no deseados.')?><br />
  <a target ="_blank" style="color: #A70B16; text-decoration:none;" href="<?php echo $this->url?>"><?php echo $this->translate('Active su cuenta haciendo click aquí')?></a>
</p>
