<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/layouts/partials/_footerPromotion.phtml $
 * @revision - $Revision: 322 $
 *   
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<section id="newAndOfers">
  <article>
    <header>
      <h3><?php echo $this->translate('novedades')?></h3>
    </header>
    <figure class="product clear">
      <img class="image" src="<?php echo APPLICATION_CDN; ?>/images/placard.jpg" alt="" />
      <figcaption class="description">
        <a><?php echo $this->translate('Ropero provenzal compacto')?></a>
      </figcaption>
      <?php echo $this->more('/');?>
    </figure>
  </article>
  <article>
    <header>
      <h3><?php echo $this->translate('novedades')?></h3>
    </header>
    <figure class="product clear">
      <img class="image" src="<?php echo APPLICATION_CDN; ?>/images/placard.jpg" alt="" />
      <figcaption class="description">
        <a><?php echo $this->translate('4 Sillas comedor punch!')?></a>
      </figcaption>
      <?php echo $this->more('/');?>
    </figure>
  </article>
  <article>
    <header>
      <h3><?php echo $this->translate('oferta!!!')?></h3>
    </header>
    <figure class="product clear">
      <img class="image" src="<?php echo APPLICATION_CDN; ?>/images/placard.jpg" alt="" />
      <figcaption class="description">
          <a><?php echo $this->translate('Gran mueble imprentero ideal estudio!')?></a>
      </figcaption>
      <?php echo $this->more('/');?>
    </figure>
  </article>
</section>