<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/layouts/partials/_productCatalog.phtml $
 * @revision - $Revision: 322 $
 *   
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<?php
echo $this->partial(
    '_productGrid.phtml',
    array(
        'products' => $this->products,
        'categoryName' => $this->categoryName,
        'subcategoryId' => $this->subcategoryId,
        'subcategoryName' => $this->subcategoryName
    )
);
?>
