<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/layouts/partials/_productGrid.phtml $
 * @revision - $Revision: 322 $
 *   
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<div id="productGrid">
<?php 
$loop = 0;
if (is_array($this->products)):?>
<section class="cycle">
  <?php
  $counter = 0;
  foreach($this->products as $product) {
      if($counter != 0 && $counter%3==0) {
          echo '<div class="separator"></div>';
      }
      echo $this->partial(
          '_productHolder.phtml',
          array(
              'product' => $product,
              'categoryName' => $this->categoryName,
              'subcategoryId' => $this->subcategoryId,
              'subcategoryName' => $this->subcategoryName
          )
      );
      $counter++;
  }
  ?>
</section>
<?php
endif;
?>
</div>
