<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/layouts/partials/behind.phtml $
 * @revision - $Revision: 322 $
 *   
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<div id="behindContainer">
  <a target="_blank" title="<?php echo $this->translate('detras del sitio')?>" href="http://ar.linkedin.com/pub/ricardo-buquet/b/767/722">
    <div id="behind" title="<?php echo $this->translate('detras del sitio')?>"></div>
  </a>
</div>