<?php
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:14:39 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/models/Category.php $
 * @revision - $Revision: 321 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:14:39 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Category.php 321 2011-12-31 05:14:39Z enkil2003 $
 */
class Category extends BaseCategory
{
    public function preSave($event)
    {
        // sets order default value
        if(!is_int($this->order)) {
            $q = Doctrine_Query::create()
                ->select('MAX(c.order) order')
                ->from('Category c')->fetchArray();
            $this->order = $q[0]['order']+1;
        }
    }
    /**
     * Returns all categories from model
     * @return array
     */
    public function getAll()
    {
        $q = Doctrine_Query::create()
            ->select('c.id, c.name')
            ->from('Category c')
            ->orderBy('c.order');
        return $q->fetchArray();
    }
    
    public static function getCategoriesAndSubcategories()
    {
        $q = Doctrine_Query::create()
            ->select('c.id, c.name, s.name')
            ->from('Category c')
            ->innerJoin('c.Subcategories s');
        return $q->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
    }
}