<?php
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:14:39 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/models/Contact.php $
 * @revision - $Revision: 321 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:14:39 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */

/**
 * Contact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Contact.php 321 2011-12-31 05:14:39Z enkil2003 $
 */
class Contact extends BaseContact
{
    /**
     * Saves the new contact to the database
     * @param array key value arrays to be saved as contact into to the database
     * @return void
     */
    public static function createContact($data)
    {
        $contact = new self();
        // si soy usuario lo asocio
        $user = Zend_Auth::getInstance()->getIdentity();
        $contact->user_id = $user? $user['id']:null;
        // guardo los datos
        foreach($data as $key => $value) {
            $contactdata = new Contactdata();
            $contactdata->field = $key;
            $contactdata->value = $value;
            $contact->Contactdata[] = $contactdata;
        }
        $contact->save();
    }
}