<?php
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:14:39 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/models/Orders.php $
 * @revision - $Revision: 321 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:14:39 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */

/**
 * Orders
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Orders.php 321 2011-12-31 05:14:39Z enkil2003 $
 */
class Orders extends BaseOrders
{
    /**
     * Devuelve los detalles de una orden. Los detalles estan conformados por los productos, su precio al momento de la
     * compra cantidades, imagenes del producto.
     * @TODO que pasas si borro un producto? estoy cargando las imagenes, que pasa con este historial?
     * @param int $orderId Numero de orden del cual quiero saber el detalle
     * @return array Array multidimensional con los productos, e imagenes de la orden
     */
    public static function getOrderdetails($orderId)
    {
        $details = Doctrine_Query::create()
            ->select('od.*, i.*, p.*')
            ->from('Orderdetail od')
            ->innerJoin('od.Products p')
            ->innerJoin('p.Images i')
            ->where('od.Order = ?', $orderId)
            ->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
        return $details;
    }
    /**
     * La orden es timestampable ya que guarda la hora de creación
     * @TODO agregar updated_at
     * @see BaseOrders::setUp()
     */
    public function setUp()
    {
        $this->actAs(
            'Timestampable',
            array( 
                'created' => array(
                    'name' => 'created_at',
                    'type' => 'timestamp',
                    'format' => 'Y-m-d H:m:s',
                    'disabled' => false,
                    'options' => array()
                ),
                'updated' => array(
                    'disabled' => true,
                    'options' =>  array()
                )
            )
        ); 
    }
}