<?php
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:14:39 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/models/Userdata.php $
 * @revision - $Revision: 321 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:14:39 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */

/**
 * Userdata
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Userdata.php 321 2011-12-31 05:14:39Z enkil2003 $
 */
class Userdata extends BaseUserdata
{
    public function getFullNameByUserId($id)
    {
        // find the user name
        $row = Doctrine_Query::create()
            ->select('ud.value')
            ->from('Userdata ud')
            ->where('ud.User = ?', $id)
            ->andWhere('ud.field = ?', 'name')
            ->fetchOne(array(), Doctrine_Core::HYDRATE_ARRAY);
        $name = $row['value'];
        
        // find the user lastname
        $row = Doctrine_Query::create()
            ->select('ud.value')
            ->from('Userdata ud')
            ->where('ud.User = ?', $id)
            ->andWhere('ud.field = ?', 'lastname')
            ->fetchOne(array(), Doctrine_Core::HYDRATE_ARRAY);
        $lastname = $row['value'];
        
        return "$name $lastname";
    }
}