<?php

/**
 * BaseSubcategoriesHasProducts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $subcategories_id
 * @property integer $products_id
 * @property Subcategories $Subcategories
 * @property Products $Products
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: BaseSubcategoriesHasProducts.php 321 2011-12-31 05:14:39Z enkil2003 $
 */
abstract class BaseSubcategoriesHasProducts extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('subcategories_has_products');
        $this->hasColumn('subcategories_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('products_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Subcategories', array(
             'local' => 'subcategories_id',
             'foreign' => 'id'));

        $this->hasOne('Products', array(
             'local' => 'products_id',
             'foreign' => 'id'));
    }
}