<?php

/**
 * BasePrivilege
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $rol
 * @property integer $resource
 * @property Resource $Resource
 * @property Rol $Rol
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: BasePrivilege.php 321 2011-12-31 05:14:39Z enkil2003 $
 */
abstract class BasePrivilege extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('privilege');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('rol', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('resource', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Resource', array(
             'local' => 'resource',
             'foreign' => 'id'));

        $this->hasOne('Rol', array(
             'local' => 'rol',
             'foreign' => 'id'));
    }
}