<?php

/**
 * BaseRol
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $rol
 * @property integer $inherit
 * @property Doctrine_Collection $Rol
 * @property Doctrine_Collection $Privilege
 * @property Doctrine_Collection $User
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: BaseRol.php 321 2011-12-31 05:14:39Z enkil2003 $
 */
abstract class BaseRol extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('rol');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('rol', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('inherit', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Rol', array(
             'local' => 'id',
             'foreign' => 'inherit'));

        $this->hasMany('Privilege', array(
             'local' => 'id',
             'foreign' => 'rol'));

        $this->hasMany('User', array(
             'local' => 'id',
             'foreign' => 'rol'));
    }
}