<?php
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 04:41:19 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/views/scripts/helpers/cartNavigation.phtml $
 * @revision - $Revision: 325 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 04:41:19 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<ul class="steps">
  <li class="step1<?php echo $this->selected == 'step1'? ' selected':'';?>"><span class="number">1</span> <span class="text"><?php echo $this->translate("CARRITO DE COMPRAS");?></span></li>
  <li class="step2<?php echo $this->selected == 'step2'? ' selected':'';?>"><span class="number">2</span> <span class="text"><?php echo $this->translate("MODO DE ENTREGA");?></span></li>
  <li class="step3<?php echo $this->selected == 'step3'? ' selected':'';?>"><span class="number">3</span> <span class="text"><?php echo $this->translate("MEDIO DE PAGO");?></span></li>
</ul>