<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/views/scripts/helpers/subcategories.phtml $
 * @revision - $Revision: 322 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<div id="subcategoriesColumn" class="span-5 categories">
  <div class="subcategoriesMargin">
    <h3><?php echo $this->escape($this->parentCategoryName);?></h3>
    <menu>
<?php 
foreach($this->subcategories as $item):
?>
       <li>
         <a href="/showroom/<?php echo $this->parentCategoryName; ?>/<?php echo $item['id']; ?>/<?php echo $this->escape($href = str_replace(' ', '-', $item['name'])); ?>"
           class="<?php echo ($href == $this->activeSubcategory)? 'active':''; ?>" >
           <?php echo $this->escape($item['name']); ?>
         </a>
       </li>
<?php
endforeach;
?>
    </menu>
  </div>
</div>