<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2012-01-01 02:11:07 -0300 (Sun, 01 Jan 2012) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/views/scripts/cart/_step4.phtml $
 * @revision - $Revision: 330 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2012-01-01 02:11:07 -0300 (Sun, 01 Jan 2012) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<div class="step4Holder">
  <div class="receptionSelection">
  <?php
  echo $this->cartNavigation('step4');
  ?>
  </div>
  <h4><?php echo $this->translate("MUCHAS GRACIAS!!")?> Bernardo!</h4>
  <p><?php echo $this->translate("Hemos enviado un <span>MAIL DE CONFIRMACIÓN</span> a tu casilla de correo.<br />
    A la brevedad un representante de Vassilymas! se pondra en contacto con vos<br />
    para coordinar el PAGO, COSTO DE ENVIO y ENTREGA de tu compra.");?></p>
  <p><?php echo $this->translate("Si tenes alguna duda o consulta escribinos a info@vassilymas.com.ar<br />o llamanos al");?> 011-4742-2687</p>
</div>