<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author$
 * @date - $Date$
 * 
 * @filesource - $HeadURL$
 * @revision - $Revision$
 * 
 * @LastChangedBy $LastChangedBy$
 * @lastChangedDate - $LastChangedDate$
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<?php $this->placeholder('catalog')->captureStart(); ?>
<div class="step4Holder">
  <h4><?php echo $this->translate("MUCHAS GRACIAS!!!")?> <?php echo $this->name ?></h4>
  <p><?php echo $this->translate("Hemos enviado un <span>MAIL DE CONFIRMACIÓN</span> a tu casilla de correo.<br />
    A la brevedad un representante de Vassilymas! se pondra en contacto con vos<br />
    para coordinar el PAGO, COSTO DE ENVIO y ENTREGA de tu compra.");?></p>
  <p><?php echo $this->translate("Si tenes alguna duda o consulta escribinos a info@vassilymas.com.ar<br />o llamanos al");?> 011-4742-2687</p>
</div>
<?php $this->placeholder('catalog')->captureEnd(); ?>