<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author$
 * @date - $Date$
 * 
 * @filesource - $HeadURL$
 * @revision - $Revision$
 * 
 * @LastChangedBy $LastChangedBy$
 * @lastChangedDate - $LastChangedDate$
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<?php $this->placeholder('catalog')->captureStart(); ?>
Esto es un mock temporario
<?php $this->placeholder('catalog')->captureEnd(); ?>