<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/modules/admin/views/scripts/category/index.phtml $
 * @revision - $Revision: 322 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<?php 
$this->placeholder('catalog')->captureStart();
?>
<div id="adminPanel">
  <form id="categoryForm" method="post" action="<?php echo $this->form->getAction() ?>">
    <div id="categoryNameContainer">
      <label for="name">Nombre de categoría</label>
      <?php echo $this->form->getElement('name');?>
        <div class="error<?php if($this->form->getElement('name')->hasErrors()):?> show<?php endif;?>">
          Debe ingresar un nombre
        </div>
      <?php ?>
    </div>
    <div id="submitContainer">
      <?php echo $this->form->getElement('submit'); ?>
    </div>
  </form>
</div>
<script>
$("#categoryForm").validator();
</script>
<style>
/* error message */
.error {
  /* supply height to ensure consistent positioning for every browser */
  height:15px;
  background-color:#FFFE36;
  border:1px solid #E1E16D;
  font-size:11px;
  color:#000;
  padding:3px 10px;
  margin-left:-2px;


  /* CSS3 spicing for mozilla and webkit */
  -moz-border-radius:4px;
  -webkit-border-radius:4px;
  -moz-border-radius-bottomleft:0;
  -moz-border-radius-topleft:0;
  -webkit-border-bottom-left-radius:0;
  -webkit-border-top-left-radius:0;

  -moz-box-shadow:0 0 6px #ddd;
  -webkit-box-shadow:0 0 6px #ddd;
}


</style>
<?php 
$this->placeholder('catalog')->captureEnd();
?>