<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/views/scripts/index/index.phtml $
 * @revision - $Revision: 322 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<?php $this->placeholder('headerPromotion')->captureStart(); ?>
<section id="promotion">
  <div id="imagepromotion" class="span-14"><img src="<?php echo APPLICATION_CDN; ?>/images/promotion.jpg" width="550" height="403" alt="" /></div>
  <div id="descriptionpromotion" class="span-9 last"><img src="<?php echo APPLICATION_CDN; ?>/images/promotionText.png" width="350" height="403" alt="" /></div>
</section>
<?php $this->placeholder('headerPromotion')->captureEnd(); ?>