<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/views/scripts/index/newsletter.phtml $
 * @revision - $Revision: 322 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<?php $this->placeholder('catalog')->captureStart(); ?>
<section id="newsletterSubscribeHolder">
  <fieldset>
    <legend><?php echo $this->translate('SUSCRIBITE AL NEWSLETTER')?></legend>
    <div class="disclaimer">
      <form method="post" action="/newsletter">
          <input type="email" name="email" placeholder="<?php echo $this->translate('Ingrese su email')?>" />
          <input type="text" name="name" placeholder="<?php echo $this->translate('Nombre')?>" />
          <button id="send" type="button" name="submit"><?php echo $this->translate('ENVIAR')?></button>
        </form>
    </div>
  </fieldset>
</section>
<?php $this->placeholder('catalog')->captureEnd(); ?>