<?php 
/**
 * Vassilymas
 *
 * @license - $License: http://www.gnu.org/licenses/gpl.txt $
 *
 * @author - $Author: enkil2003 $
 * @date - $Date: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @filesource - $HeadURL: https://subversion.assembla.com/svn/vassilymas/trunk/src/application/views/scripts/catalog/index.phtml $
 * @revision - $Revision: 322 $
 * 
 * @LastChangedBy $LastChangedBy: enkil2003 $
 * @lastChangedDate - $LastChangedDate: 2011-12-31 02:17:49 -0300 (Sat, 31 Dec 2011) $
 * 
 * @copyright - Copyright: (c) 2011 and future, Ricardo Buquet
 */
?>
<?php $this->placeholder('catalogLeftColumn')->captureStart(); ?>
<?php echo $this->subcategories(); ?>
<?php $this->placeholder('catalogLeftColumn')->captureEnd(); ?>
<?php $this->placeholder('catalog')->captureStart(); ?>
<?php
echo $this->pagination();
?>
<?php
echo $this->partial(
    '_productCatalog.phtml',
    array(
        'products' => $this->products,
        'categoryName' => $this->category,
        'subcategoryId' => $this->subcategoryId,
        'subcategoryName' => $this->subcategory
    )
);
?>
<?php $this->placeholder('catalog')->captureEnd(); ?>